server:
  port: 10002

spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/xe}
    username: ${DB_USERNAME:DONGYANG}
    password: ${DB_PASSWORD:1234}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.OracleLegacyDialect
    show-sql: true

elevenlabs:
  base-url: https://api.elevenlabs.io
  api-key: ${ELEVENLABS_API_KEY}
#  project-id: K5GMjJiqLM5Ki9JHJEBG
  model-id: eleven_multilingual_v2
  default-voice-id: 21m00Tcm4TlvDq8ikWAM
  output-format: mp3_44100_128
jwt:
  secret: ${JWT_SECRET:change-me-in-prod}

openai:
  api-key: ${OPENAI_API_KEY:}

