server:
  port: 10002
  servlet:
    context-path: /
  forward-headers-strategy: framework
spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/xe}
    username: ${DB_USERNAME:DONGYANG}
    password: ${DB_PASSWORD:1234}
    mail:                                    # 서버 개발 버전
      host: mail
      port: 587
      username: sender@aiinviewer.co.kr
      password: ${MAIL_PASSWORD}
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.mime.charset: UTF-8
        mail.smtp.ssl.trust: "mail"
#  mail:                                      ## 로컬 개발 버전
#    host: mail.aiinviewer.co.kr
#    port: 587
#    username: sender@aiinviewer.co.kr
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
#      mail.smtp.ssl.trust: "mail.aiinviewer.co.kr"
#      mail.mime.charset: UTF-8

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.OracleLegacyDialect
    show-sql: true

elevenlabs:
  base-url: https://api.elevenlabs.io
  api-key: ${ELEVENLABS_API_KEY}
  #  project-id: K5GMjJiqLM5Ki9JHJEBG
  model-id: eleven_multilingual_v2
  default-voice-id: 21m00Tcm4TlvDq8ikWAM
  output-format: mp3_44100_128
jwt:
  secret: ${JWT_SECRET:change-me-in-prod}

openai:
  api-key: ${OPENAI_API_KEY:}

logging:
  level:
    org.springframework.security: DEBUG
app:
  mail:
    from: "AI-Inviewer <no-reply@aiinviewer.co.kr>"